{
  flake.nixosModules.hostLegion =
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-ea07a75e-e401-4830-8cea-3a1ed2f3a248";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ea07a75e-e401-4830-8cea-3a1ed2f3a248".device = "/dev/disk/by-uuid/ea07a75e-e401-4830-8cea-3a1ed2f3a248";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E83C-2EC8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
};

}
