{
  flake.nixosModules.hostAlae =
    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "xhci_pci"
        "nvme"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/mapper/luks-2d25ef7c-4b74-4703-8c11-346185fc1916";
        fsType = "ext4";
      };

      boot.initrd.luks.devices."luks-2d25ef7c-4b74-4703-8c11-346185fc1916".device =
        "/dev/disk/by-uuid/2d25ef7c-4b74-4703-8c11-346185fc1916";

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/8869-33B7";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [
        { device = "/dev/disk/by-uuid/65139071-24e1-4bf9-8a43-44267c445809"; }
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
